import re
from pathlib import Path
from typing import Dict, List

from .config import SectionConfig


def slugify(topic: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", topic.lower()).strip("-")


def ensure_output_dir(base_dir: Path, topic: str) -> Path:
    output_dir = base_dir / slugify(topic)
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def write_section(output_dir: Path, section: SectionConfig, content: str) -> Path:
    file_path = output_dir / section.filename
    file_path.write_text(content, encoding="utf-8")
    return file_path


def write_readme(
    output_dir: Path,
    topic: str,
    model: str,
    sections: List[SectionConfig],
    word_counts: Dict[int, int],
) -> Path:
    lines = [
        f"# Interview Prep: {topic}\n\n",
        f"> Generated by **prep-master** | Model: `{model}`\n\n",
        "## Sections\n\n",
    ]
    for s in sections:
        wc = word_counts.get(s.index, 0)
        lines.append(f"- [{s.index}. {s.title}]({s.filename}) — {wc:,} words\n")

    readme_path = output_dir / "README.md"
    readme_path.write_text("".join(lines), encoding="utf-8")
    return readme_path
