#!/usr/bin/env python3
"""Assemble the MkDocs `docs/` tree from output/ + site_data/.

Single source of truth is output/ (written by prep-master) plus the curated,
version-controlled enrichment in site_data/. This script is idempotent: it
fully regenerates docs/ on every run, so re-running after prep-master adds new
topics just works once they are added to site_data/clusters.yml.

Existing topic prose is copied verbatim — enrichment is only ever *appended*.
"""
from __future__ import annotations

import shutil
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "output"
SITE_DATA = REPO / "site_data"
DOCS = REPO / "docs"

PDF_PATH = "pdf/ai-engineer-learning-hub.pdf"  # with-pdf output_path (relative)
# Absolute URL for the landing-page button: an external link is not subject
# to mkdocs link validation, so the strict (no-PDF) build stays clean while
# the link still resolves on the deployed site once the PDF is built in CI.
PDF_URL = "https://asadani.github.io/ai-engineer-learning-hub/" + PDF_PATH

# Print-only: shows in the WeasyPrint-rendered PDF, never on the live site
# (screen media). WeasyPrint repeats a position:fixed element on every page.
EXTRA_CSS = """/* generated by scripts/build_docs.py — do not edit */
@media print {
  /* Name watermark — repeats on every PDF page (WeasyPrint repeats fixed). */
  body::before {
    content: "Anuj Sadani \\00B7 asadani.github.io";
    position: fixed;
    top: 45%;
    left: -10%;
    right: -10%;
    text-align: center;
    font-size: 64px;
    font-weight: 700;
    color: rgba(0, 0, 0, 0.06);
    transform: rotate(-30deg);
    z-index: 0;
    pointer-events: none;
    white-space: nowrap;
  }

  /* WeasyPrint's CSS-Grid support crashes on Material's grid-template
     functions ('FunctionBlock' object is not subscriptable). Flatten any
     grid to block for the PDF only; the live site keeps its card layout. */
  .md-typeset .grid,
  .md-typeset .grid.cards,
  .grid,
  .grid.cards {
    display: block !important;
    grid-template-columns: none !important;
    grid-template-rows: none !important;
    grid-template: none !important;
  }
  .md-typeset .grid > *,
  .md-typeset .grid.cards > :is(ul, ol, li, .card),
  .grid > * {
    width: auto !important;
    margin: 0 0 0.6rem 0 !important;
  }
}
"""

SECTION_FILES = [
    "1_High_Level_Overview.md",
    "2_Key_Technical_Concepts.md",
    "3_Products_Tools.md",
    "4_Tradeoffs_Comparisons.md",
    "5_Use_Cases.md",
    "6_Measurement_Evaluation.md",
    "7_What_to_Measure_How.md",
    "8_Interview_Questions.md",
]


def load_yaml(name: str) -> dict:
    path = SITE_DATA / name
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def fix_readme_links(text: str) -> str:
    """README.md is published as index.md; keep any back-references valid."""
    return text.replace("](README.md)", "](index.md)").replace(
        "](./README.md)", "](index.md)"
    )


def build():
    clusters_cfg = load_yaml("clusters.yml")
    links_cfg = load_yaml("links.yml")
    glossary_cfg = load_yaml("glossary.yml")
    courses_cfg = load_yaml("courses.yml")
    updates_cfg = load_yaml("updates.yml")

    site = clusters_cfg.get("site", {})
    clusters = clusters_cfg.get("clusters", [])

    # Global map: topic dir -> (cluster_slug, topic_slug, title)
    topic_index: dict[str, tuple[str, str, str]] = {}
    for cluster in clusters:
        for topic in cluster["topics"]:
            topic_index[topic["dir"]] = (
                cluster["slug"],
                topic["slug"],
                topic["title"],
            )

    # Fresh docs/ every run.
    if DOCS.exists():
        shutil.rmtree(DOCS)
    DOCS.mkdir(parents=True)

    skipped: list[str] = []

    # Topics actually generated (so we never emit links to missing pages).
    built_dirs = {
        t["dir"]
        for c in clusters
        for t in c["topics"]
        if (OUTPUT / t["dir"]).is_dir()
    }

    built_cluster_slugs: list[str] = []

    # ---- Topic pages -----------------------------------------------------
    for cluster in clusters:
        cluster_built = [
            t for t in cluster["topics"] if t["dir"] in built_dirs
        ]
        if not cluster_built:
            continue  # whole cluster not generated yet — omit entirely
        built_cluster_slugs.append(cluster["slug"])
        cdir = DOCS / cluster["slug"]
        cdir.mkdir(parents=True, exist_ok=True)
        topic_nav = []
        for topic in cluster["topics"]:
            src = OUTPUT / topic["dir"]
            if not src.is_dir():
                # Not yet generated by prep-master — skip, don't fail the build.
                skipped.append(topic["dir"])
                continue
            tdir = cdir / topic["slug"]
            tdir.mkdir(parents=True, exist_ok=True)

            # README.md -> index.md (+ appended enrichment).
            readme = src / "README.md"
            body = fix_readme_links(readme.read_text(encoding="utf-8")) if readme.exists() else f"# {topic['title']}\n"
            body += render_updates(updates_cfg.get(topic["dir"]))
            body += render_official_sources(links_cfg.get(topic["dir"]))
            body += render_related(cluster, topic, topic_index, built_dirs)
            (tdir / "index.md").write_text(body, encoding="utf-8")

            # Verbatim section copies.
            present_sections = []
            for fname in SECTION_FILES:
                fsrc = src / fname
                if not fsrc.exists():
                    continue
                (tdir / fname).write_text(
                    fix_readme_links(fsrc.read_text(encoding="utf-8")),
                    encoding="utf-8",
                )
                present_sections.append(fname)

            (tdir / ".pages").write_text(
                "title: " + yaml_str(topic["title"]) + "\n"
                + "nav:\n"
                + "  - Overview: index.md\n"
                + "".join(f"  - {f}\n" for f in present_sections),
                encoding="utf-8",
            )
            topic_nav.append(topic["slug"])

        (cdir / ".pages").write_text(
            "title: " + yaml_str(cluster["title"]) + "\n"
            + "nav:\n"
            + "".join(f"  - {s}\n" for s in topic_nav),
            encoding="utf-8",
        )

    # ---- Landing page ----------------------------------------------------
    (DOCS / "index.md").write_text(
        render_landing(site, clusters, built_dirs), encoding="utf-8"
    )

    # ---- Glossary --------------------------------------------------------
    (DOCS / "glossary.md").write_text(
        render_glossary(glossary_cfg), encoding="utf-8"
    )

    # ---- Courses ---------------------------------------------------------
    (DOCS / "courses.md").write_text(
        render_courses(courses_cfg), encoding="utf-8"
    )

    # ---- Abbreviations (auto-appended site-wide -> hover tooltips) --------
    # Static assets (regenerated every run since docs/ is wiped).
    assets = DOCS / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    (assets / "extra.css").write_text(EXTRA_CSS, encoding="utf-8")

    inc = DOCS / "includes"
    inc.mkdir(parents=True, exist_ok=True)
    (inc / ".pages").write_text("hide: true\n", encoding="utf-8")
    (inc / "abbreviations.md").write_text(
        render_abbreviations(glossary_cfg), encoding="utf-8"
    )

    # ---- Root nav order --------------------------------------------------
    root_nav = ["  - Home: index.md\n"]
    root_nav += [f"  - {s}\n" for s in built_cluster_slugs]
    root_nav += ["  - Glossary: glossary.md\n", "  - Free Courses & Certs: courses.md\n"]
    (DOCS / ".pages").write_text(
        "nav:\n" + "".join(root_nav), encoding="utf-8"
    )

    declared = sum(len(c["topics"]) for c in clusters)
    built = declared - len(skipped)
    print(f"Built docs/: {len(clusters)} clusters, {built}/{declared} topics.")
    if skipped:
        print(
            f"Skipped {len(skipped)} not-yet-generated topic(s): "
            + ", ".join(sorted(skipped))
        )


def yaml_str(s: str) -> str:
    """Quote strings safely for the tiny YAML we emit into .pages files."""
    return '"' + s.replace('"', '\\"') + '"'


def render_updates(entry) -> str:
    if not entry:
        return ""
    as_of = entry.get("as_of", "2026")
    out = [
        "\n\n",
        f'!!! warning "2026 Update — what changed since this was written (as of {as_of})"\n\n',
    ]
    for p in entry.get("points", []):
        out.append(f"    - {p}\n")
    srcs = entry.get("sources", [])
    if srcs:
        out.append("\n    **Sources:** ")
        out.append(
            " · ".join(f"[{s['title']}]({s['url']})" for s in srcs)
        )
        out.append("\n")
    return "".join(out)


def render_official_sources(entry) -> str:
    if not entry:
        return ""
    out = ["\n\n---\n\n", '!!! info "Official Sources & Further Reading"\n\n']
    for item in entry.get("sources", []):
        note = f" — {item['note']}" if item.get("note") else ""
        out.append(f"    - [{item['title']}]({item['url']}){note}\n")
    return "".join(out)


def render_related(cluster, topic, topic_index, built_dirs) -> str:
    seen: set[str] = set()
    ordered: list[str] = []

    # Same-cluster siblings first.
    for sib in cluster["topics"]:
        if sib["dir"] != topic["dir"] and sib["dir"] not in seen:
            ordered.append(sib["dir"])
            seen.add(sib["dir"])
    # Then explicit cross-cluster edges.
    for rel in topic.get("related", []):
        if rel not in seen and rel in topic_index:
            ordered.append(rel)
            seen.add(rel)

    # Only link to topics that have actually been generated.
    ordered = [d for d in ordered if d in built_dirs]

    if not ordered:
        return ""

    out = ["\n\n", '!!! tip "Related Topics"\n\n']
    src_cluster = cluster["slug"]
    for d in ordered:
        cslug, tslug, title = topic_index[d]
        rel_path = f"../../{cslug}/{tslug}/" if cslug != src_cluster else f"../{tslug}/"
        out.append(f"    - [{title}]({rel_path})\n")
    return "".join(out)


def render_landing(site, clusters, built_dirs) -> str:
    name = site.get("name", "AI Engineer Learning Hub")
    tagline = site.get("tagline", "")
    lines = [
        f"# {name}\n",
        "",
        f"{tagline}\n" if tagline else "",
        "",
        "A curated, cross-linked study library for AI-era engineers. Pick a",
        "cluster below, or use the search bar (press `/`) to jump to any term.",
        "",
        "<div class=\"grid cards\" markdown>",
        "",
    ]
    for c in clusters:
        topics = [t for t in c["topics"] if t["dir"] in built_dirs]
        if not topics:
            continue
        first = topics[0]
        icon = c.get("icon", "material/book-open-variant").replace("/", "-")
        lines.append(
            f"-   :{icon}:{{ .lg .middle }} "
            f"__[{c['title']}]({c['slug']}/{first['slug']}/)__"
        )
        lines.append("")
        lines.append(f"    {c['description']}")
        lines.append("")
        for t in topics:
            lines.append(f"    - [{t['title']}]({c['slug']}/{t['slug']}/)")
        lines.append("")
    lines += [
        "</div>",
        "",
        "---",
        "",
        "**New here?** Start with the [Glossary](glossary.md) for key terms, or the",
        "[Free Courses & Certifications](courses.md) hub to build a learning path.",
        "",
        f"[:material-file-pdf-box: __Download the full hub as a PDF__]({PDF_URL})",
        "{ .md-button }",
        "",
        "Every topic follows the same 8-section structure: Overview → Key Concepts →",
        "Tools → Tradeoffs → Use Cases → Measurement → What to Measure → Interview",
        "Questions. Hover any **dotted term** for an inline definition.",
        "",
        "---",
        "",
        "© 2026 Anuj Sadani · anuj.k.sadani@gmail.com · "
        "[asadani.github.io](https://asadani.github.io/). "
        "Content licensed [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
        " — free to share and adapt with attribution.",
        "",
    ]
    return "\n".join(lines)


def render_glossary(cfg) -> str:
    terms = cfg.get("terms", [])
    lines = [
        "# Glossary",
        "",
        "Key terms across all clusters. These also appear as hover tooltips on",
        "every page (look for the dotted underline).",
        "",
    ]
    by_letter: dict[str, list] = {}
    for t in sorted(terms, key=lambda x: x["term"].lower()):
        by_letter.setdefault(t["term"][0].upper(), []).append(t)
    for letter in sorted(by_letter):
        lines.append(f"## {letter}")
        lines.append("")
        for t in by_letter[letter]:
            link = f" [↗]({t['url']})" if t.get("url") else ""
            lines.append(f"**{t['term']}**{link}\n: {t['definition']}")
            lines.append("")
    return "\n".join(lines)


def render_abbreviations(cfg) -> str:
    # pymdownx abbreviations: *[TERM]: plain-text definition (single line).
    lines = ["<!-- auto-generated by scripts/build_docs.py — do not edit -->", ""]
    for t in cfg.get("terms", []):
        defn = " ".join(str(t["definition"]).split())
        lines.append(f"*[{t['term']}]: {defn}")
    return "\n".join(lines) + "\n"


def render_courses(cfg) -> str:
    lines = [
        "# Free Courses & Certifications",
        "",
        "Verified **free** (or free-to-audit) learning resources, grouped by",
        "provider. Cluster tags show which topics each maps to best.",
        "",
    ]
    for prov in cfg.get("providers", []):
        lines.append(f"## {prov['name']}")
        lines.append("")
        if prov.get("note"):
            lines.append(f"_{prov['note']}_")
            lines.append("")
        lines.append("| Course | Cost | Clusters |")
        lines.append("|--------|------|----------|")
        for c in prov.get("courses", []):
            clusters = ", ".join(c.get("clusters", [])) or "—"
            lines.append(
                f"| [{c['title']}]({c['url']}) | {c.get('cost','Free')} | {clusters} |"
            )
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    build()
